name: Docker CI/CD Demo

# Chạy workflow khi có sự kiện push lên nhánh main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên máy Ubuntu

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Login vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-hello-ci-cd:latest
